/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.myapp;

import javax.swing.JButton;
import javax.swing.JPanel;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JTextField;

public class NewJPanel extends JPanel  {
    JButton[] buttons;
    String[] label = {"%", "CE", "C", "DEL", "7", "8", "9", "X", "4", "5", "6", "-", "1", "2", "3", "+", "C", "0", ",", "="};
    private JTextField display; // Ajout d'un champ pour le display
    private String operator;
    private double firstOperand;
    private boolean isOperatorPressed;
            
    public NewJPanel(JTextField display) {
        this.display = display; // Initialisation du display
        initComponents();
        buttons = new JButton[label.length];
        setLayout(new GridLayout(5, 4));

        for (int i = 0; i < label.length; i++) {
            buttons[i] = new JButton(label[i]);
            add(buttons[i]);
            buttons[i].addActionListener((ActionListener) this);
        }
        
        operator ="";
        firstOperand = 0;
        isOperatorPressed = false;
    }
    public void actionPerformed(ActionEvent e){
        JButton source = (JButton) e.getSource();
        String command = source.getActionCommand();
        
        if(command.matches("\\d")|| command.equals(".")){
             if(isOperatorPressed){
                 display.setText(command);
                 isOperatorPressed = false;
             }       
        }
        else if(command.matches("[+\\-*/]")){
            firstOperand = Double.parseDouble(display.getText());
            operator = command;
            isOperatorPressed = true;
        }
        else{
            
            switch (command) {
            case "=" -> {
                double secondOperand = Double.parseDouble(display.getText()); // Stocke le deuxième opérande
                double result = 0;
                switch (operator) {
                    case "+" -> result = firstOperand + secondOperand;
                    case "-" -> result = firstOperand - secondOperand;
                    case "*" -> result = firstOperand * secondOperand;
                    case "/" -> result = firstOperand / secondOperand;
                }
                display.setText(String.valueOf(result)); // Affiche le résultat
                operator = ""; // Réinitialise l'opérateur
                isOperatorPressed = false; // Réinitialise l'état de l'opérateur
                }

            case "C" -> {
                display.setText(""); // Réinitialise l'affichage
                firstOperand = 0; // Réinitialise le premier opérande
                operator = ""; // Réinitialise l'opérateur
                isOperatorPressed = false; // Réinitialise l'état de l'opérateur
                }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

    private void initComponents() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
